# Generated by Django 4.0.1 on 2022-06-11 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_alter_certificate_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideinfo',
            name='lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 11, 11, 10, 53, 758952, tzinfo=utc)),
        ),
    ]
