# Generated by Django 4.0.1 on 2022-06-11 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_alter_guideinfo_lastgdelstseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideinfo',
            name='lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 11, 11, 24, 2, 38758, tzinfo=utc)),
        ),
    ]
