# Generated by Django 4.0.1 on 2022-06-12 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_alter_guideinfo_lastgdelstseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideinfo',
            name='lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 16, 0, 48, 453445, tzinfo=utc)),
        ),
    ]
