# Generated by Django 4.0.1 on 2022-03-27 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=12)),
                ('rans', models.CharField(max_length=12)),
                ('rques', models.CharField(max_length=12)),
                ('birthday', models.DateField()),
                ('token', models.CharField(default='', max_length=200)),
                ('is_varified', models.BooleanField(default=False)),
                ('h', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
