# Generated by Django 4.0.1 on 2022-03-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calc',
            name='h',
        ),
    ]
