# Generated by Django 4.0.1 on 2022-04-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_calc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='image',
            field=models.FileField(default=None, upload_to='profile_pics'),
        ),
    ]
