# Generated by Django 4.0.1 on 2022-04-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_alter_calc_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calc',
            name='rans',
        ),
        migrations.RemoveField(
            model_name='calc',
            name='rques',
        ),
        migrations.AlterField(
            model_name='calc',
            name='image',
            field=models.FileField(default='profile.png', upload_to='profile_pics'),
        ),
    ]
