# Generated by Django 4.0.1 on 2022-04-20 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calc', '0007_fields_calc_fdsexpert_calc_fdsneeded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuedby', models.CharField(blank=True, max_length=500)),
                ('certificate', models.FileField(blank=True, upload_to='certificates')),
                ('fd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.fields')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
