# Generated by Django 4.0.1 on 2022-05-25 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calc', '0008_certificates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField()),
                ('time_asked', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('fd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.fields')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to=settings.AUTH_USER_MODEL)),
                ('guidee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_asked'],
            },
        ),
    ]
