# Generated by Django 4.0.1 on 2022-05-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc',
            name='guide_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='calc',
            name='guidee_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='calc',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
