# Generated by Django 4.0.1 on 2022-06-01 02:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calc', '0011_calc_certificates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='calc',
            new_name='usrinfo',
        ),
    ]
