# Generated by Django 4.0.1 on 2022-06-01 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_rename_calc_usrinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usrinfo',
            old_name='user',
            new_name='usr',
        ),
    ]
