# Generated by Django 4.0.1 on 2022-06-01 05:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_rename_user_usrinfo_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrinfo',
            name='guide_connectmode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usrinfo',
            name='guide_lastgdelstseen',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 5, 29, 38, 381546, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='usrinfo',
            name='guidee_availablemode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usrinfo',
            name='questions_asked',
            field=models.ManyToManyField(related_name='questions_asked', to='calc.Question'),
        ),
        migrations.AddField(
            model_name='usrinfo',
            name='questions_byguidees',
            field=models.ManyToManyField(related_name='questions_byguidees', to='calc.Question'),
        ),
    ]
