# Generated by Django 4.0.1 on 2022-06-01 06:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_usrinfo_guide_connectmode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_asked',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 6, 1, 6, 4, 33, 361300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usrinfo',
            name='guide_lastgdelstseen',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 6, 1, 6, 4, 33, 362570, tzinfo=utc)),
        ),
    ]
