# Generated by Django 4.0.1 on 2022-06-01 06:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_alter_question_time_asked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_asked',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 6, 7, 27, 848949, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usrinfo',
            name='guide_lastgdelstseen',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 6, 1, 6, 7, 27, 848949, tzinfo=utc)),
        ),
    ]
