# Generated by Django 4.0.1 on 2022-06-11 04:51

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calc', '0017_alter_question_time_asked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('status', models.CharField(default='gde_gd', max_length=15)),
                ('time_rated', models.DateTimeField(auto_now=True)),
                ('gd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_guides', to=settings.AUTH_USER_MODEL)),
                ('gde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_guidees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rvw', models.TextField()),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='gde_gd', max_length=15)),
                ('gd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rvw_guides', to=settings.AUTH_USER_MODEL)),
                ('gde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rvw_guidees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usrinfo',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='usrinfo',
            name='fdsexpert',
        ),
        migrations.RemoveField(
            model_name='usrinfo',
            name='fdsneeded',
        ),
        migrations.RemoveField(
            model_name='usrinfo',
            name='guide_connectmode',
        ),
        migrations.RemoveField(
            model_name='usrinfo',
            name='guide_lastgdelstseen',
        ),
        migrations.RemoveField(
            model_name='usrinfo',
            name='guide_rating',
        ),
        migrations.RemoveField(
            model_name='usrinfo',
            name='guidee_availablemode',
        ),
        migrations.RemoveField(
            model_name='usrinfo',
            name='guidee_rating',
        ),
        migrations.RemoveField(
            model_name='usrinfo',
            name='level',
        ),
        migrations.RemoveField(
            model_name='usrinfo',
            name='questions_asked',
        ),
        migrations.RemoveField(
            model_name='usrinfo',
            name='questions_byguidees',
        ),
        migrations.AlterField(
            model_name='question',
            name='time_asked',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 11, 4, 51, 59, 355206, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
