# Generated by Django 4.0.1 on 2022-06-11 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0021_alter_question_time_asked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_asked',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 11, 11, 24, 2, 33770, tzinfo=utc)),
        ),
    ]
