# Generated by Django 4.0.1 on 2022-06-12 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0022_alter_question_time_asked'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='no',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='time_asked',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 16, 0, 48, 448457, tzinfo=utc)),
        ),
    ]
