# Generated by Django 4.0.1 on 2022-06-14 16:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0024_alter_question_time_asked'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_asked',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 16, 49, 32, 208645, tzinfo=utc)),
        ),
    ]
