# Generated by Django 4.0.1 on 2022-06-14 16:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0025_question_ans_alter_question_time_asked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_asked',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 16, 57, 47, 591201, tzinfo=utc)),
        ),
    ]
